### ISSUE TITLE
Support for optional S3 Credentials

### ISSUE THREAD

**Issue by scottymack** [supabase/storage-api#150]
# Feature request
Support for S3 [Signature Version 4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) specifying of `access key ID` and `secret access key`.

## Is your feature request related to a problem? Please describe.
When connecting a self-hosted Supabase to a Backblaze S3 compatible bucket for storage, it requires that I pass the `access key ID` and `secret access key` as the [Credentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html#credentials) for the `S3ClientConfig` object.  I believe other S3 compatible storage options will require this same security feature, but haven't tried them myself.

## Describe the solution you'd like
Allow passing in `access key ID` and `secret access key` as optional environment variables and then include them in the `S3ClientConfig` object if present.

## Additional context
I have this working on my local version of storage-api and put up a [PR](https://github.com/supabase/storage-api/pull/151) for review/discussion.

**Comment by scottymack** [comment]
You can set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in order to get these credentials set on the `S3ClientConfig`.

**Comment by jtkeyva** [comment]
does supabase hosted version support backblaze?

**Comment by scottymack** [comment]
@jtkeyva No, you can only use backblaze through a self-hosted version

**Comment by jtkeyva** [comment]
> @jtkeyva No, you can only use backblaze through a self-hosted version

thanks. any particular reason for this? you seem to support several different providers for auth, sms, etc

**Comment by inian** [comment]
Storage-api is compatible with anything s3 compatible, but we don't offer backblaze yet on the hosted version because
- we havent tested it actively on anything other than s3. Supporting a new backend provider takes additional ongoing effort. 
- performance is probably going to be worse since our storage-api is currently hosted on aws and retrieving objects within the same aws network is going to be faster than retrieving objects over the internet. 
- We don't let users bring their own infrastructure yet (bring your own eks cluster / ec2 instance). I see bringing your own s3 / backblaze bucket as more similar to that as opposed to integrating with third party sms providers. 
- It has nothing to do with cost. We charge 21c per GB (as of today) which is at the same cost (or cheaper even) than what you would get directly from AWS. 

That being said, this is on our roadmap, just that the storage team is working on higher priority features like adding more image transformations and allowing parallel, resumable uploads.

**Comment by jtkeyva** [comment]
@inian thank you, glad to hear it's on the roadmap!
