### ISSUE TITLE
Documentation for downloading/uploading to storage is wrong

### ISSUE THREAD

**Issue by huntedman** [supabase/storage-api#175]
# Bug report

## Describe the bug

Documentation [for storage](https://supabase.com/docs/guides/storage) instructs you to create a bucket "avatars" and make it public.

I did and uploaded an image in it.
<img width="1668" alt="Screenshot 2022-08-09 at 09 42 30" src="https://user-images.githubusercontent.com/7933242/183582015-61f1e3fb-3d4d-43b0-932c-5fa6b76e50e7.png">

Now when I want to download this image, I'm instructed to 
<img width="888" alt="Screenshot 2022-08-09 at 09 47 07" src="https://user-images.githubusercontent.com/7933242/183582737-74a85898-b4d6-426c-bb7a-9ca6dfeebb3d.png">

Which is wrong, because it will make a request to bucket url
<img width="622" alt="Screenshot 2022-08-09 at 09 48 58" src="https://user-images.githubusercontent.com/7933242/183583015-729e02b7-0717-49e8-a9b9-8ef74f9571b3.png">

When instead it should be going this
![Screenshot 2022-08-09 at 09 48 00](https://user-images.githubusercontent.com/7933242/183582859-8347da02-26a1-4950-b945-efd87732c47e.png)

And the Dart docs are also out of date.

**Comment by bnjmnt4n** [comment]
Hey @huntedman! If you're following the instructions, the "download a file" JavaScript instruction actually corresponds to the one from the "upload a file" JavaScript instructions (https://supabase.com/docs/guides/storage#upload-a-file), so if you upload a file with a different name and folder, the instructions won't correspond.

Since you seem to have uploaded a file to the root in the `avatars` bucket, the proper instruction should be the following (not sure why you used `.from("public/avatars")` when you should use the bucket name (`.from("avatars")`)

```
const { data, error } = await supabase.storage.from('avatars').download('xxxxx.png')
```
