### ISSUE TITLE
Upload and download progress events. 

### ISSUE THREAD

**Issue by inian** [supabase/storage-api#23]
[Feature request](https://github.com/supabase/supabase/discussions/1073#discussioncomment-772503)

How do we go about emitting these events from the server? Does S3 support this natively? What about other storage backends like Backblaze? I do not want to add S3 only features to our server if possible.

**Comment by mgm1313** [comment]
The `@aws-sdk/lib-storage` library [exposes](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/README.md) an `.on('httpUploadProgress', (progress) => {})` method on the `Upload` instance. This `progress` object contains the `loaded` and `total` bytes of the request.

I'm not quite sure on Backblaze's capabilities to expose the upload progress. But from their docs they [claim to have a S3 compatible API](https://www.backblaze.com/b2/docs/s3_compatible_api.html). I also found a B2 library which [succeeded](https://github.com/yakovkhalinsky/backblaze-b2/blob/345e3bcc1fdbbbc879e180ee1e5952856c99c320/README.md#reference) in adding an upload progress tracker for Backblaze. So seems doable.

**Comment by grschafer** [comment]
Having upload progress would be helpful! I've looked into this a little bit and wanted to document my findings and thought process to hopefully advance this idea further.

The `httpUploadProgress` event in the AWS library is a good find! It seems like the difficulty would be passing those events back to the client somehow. Given that the `storage-api` API is a single POST request to `/storage/v1/object/{bucket}/{path}` (for uploading), it seems like the only way for the server to provide progress feedback to the client would be out-of-band, for example via a separate client connection to `storage-api` (could be polling or long-polling or websockets) or via a separate client connection to the database (could be realtime notifications of changes to a `storage.object_progress` table that `storage-api` updates). Those options add considerable server-side complexity (sharing upload-progress state between multiple `storage-api` connections or adding a noisy database table to act as pubsub) and client-side complexity (requiring multiple connections and maybe realtime-js).

The above ideas don't seem great to me, so exploring more widely brings us to the idea of changing the server-side API or, more likely, adding a separate API. Options that come to mind:
- Upload files over a duplex connection like websockets, so the server can send messages to the client about progress uploading to the storage provider. This seems doable, but unusual, so there might be surprise obstacles.
- Mimic the underlying AWS library, which bases its `httpUploadProgress` event on how many parts of a multipart upload are complete (sidenote: it does not actually emit a progress event for PutObject other than when it's complete, i.e. at 100% progress!). This approach would involve the client JS library splitting the file into chunks and making separate requests to upload each chunk. The server-side could handle making CreateMultipartUpload and CompleteMultipartUpload requests and would attach auth and forward the chunk upload requests on to the storage provider (e.g. S3).

Yuck, these ideas don't seem great either. Stepping back, I wonder if it makes sense to report progress from the server-side at all. If progress is measured client-side, we side-step the complexity of communicating progress from server to client, and we avoid adding storage-provider-specific functionality to `storage-api`. Assuming `storage-api` has relatively short timeouts and doesn't silence errors, then measuring progress client-side should be safe and reasonably accurate.

Measuring progress on the client doesn't quite fit in a `storage-api` issue, but I'll push on a bit further -- how could this work? There's a recent article about `fetch` accepting a stream body (https://web.dev/fetch-upload-streaming/), which should let us measure how many bytes fetch has read. Unfortunately, it seems this [feature is supported by no browsers](https://caniuse.com/mdn-api_request_request_readablestream_request_body) and only works in chrome by enabling `chrome://flags/#enable-experimental-web-platform-features`. Also, this feature doesn't seem to have much momentum as far as I can tell -- related issues have been open for years ([#1](https://github.com/whatwg/fetch/issues/607), [#2](https://bugs.chromium.org/p/chromium/issues/detail?id=688906)) so this functionality might not land in browsers anytime soon.

The alternative is [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload) and the `progress` events that it emits. I'm not too familiar with node and isomorphic-javascript type stuff, so I'm wondering: is it feasible to have an option or separate function in [supabase/storage-js](https://github.com/supabase/storage-js) for upload/download with `XMLHttpRequest` instead of `fetch`? (Should I open an issue about this on that repo?)

Thoughts? Hopefully I'm missing an easy, obvious answer that y'all can point out to me! If not, then hopefully the above helps clarify this issue and save time for others interested in this feature.

**Comment by grschafer** [comment]
In case it's helpful for others, here's an approach for getting upload progress with XMLHttpRequest in the browser.

In place of:
```
await supabase.storage.from(bucket).upload(path, data);
```

you could instead do the below:
```
// Typescript will give errors for accessing protected members of supabase
const url = `${supabase.supabaseUrl}/storage/v1/object/${bucket}/${path}`;
const headers = supabase._getAuthHeaders();

const req = new XMLHttpRequest();
req.upload.onprogress = updateProgress;
req.upload.onload = transferComplete;
// You might want to also listen to onabort, onerror, ontimeout
req.open("POST", url);
for (const [key, value] of Object.entries(headers)) {
  req.setRequestHeader(key, value);
}
req.send(data);

function updateProgress(e) {
  const pct = (e.loaded / e.total) * 100;
  console.log(`Upload progress = ${e.loaded} / ${e.total} = ${pct}`);
}

function transferComplete(e) {
  console.log("The transfer is complete.");
}
```

Some of the code above is directly from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#monitoring_progress).

Note that events for listening to uploads are on [XMLHttpRequest.upload](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload) and events for listening to downloads are on [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#events).

**Comment by kk21** [comment]
Since S3 provides signed urls for upload:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html

Is it possible for storage-api to call this and give us the url?
We can then try to upload to this url directly and probably able to track progress using e.g. axios on the web client.

**Comment by He1nr1chK** [comment]
Has any progress been made on this issue yet? Not work arounds but official support?

**Comment by iampopal** [comment]
Any progress on this, we need this on flutter supabase package too

**Comment by Nisthar** [comment]
progress events are much needed when uploading large files.

**Comment by Nisthar** [comment]
> In case it's helpful for others, here's an approach for getting upload progress with XMLHttpRequest in the browser.
> 
> In place of:
> 
> ```
> await supabase.storage.from(bucket).upload(path, data);
> ```
> 
> you could instead do the below:
> 
> ```
> // Typescript will give errors for accessing protected members of supabase
> const url = `${supabase.supabaseUrl}/storage/v1/object/${bucket}/${path}`;
> const headers = supabase._getAuthHeaders();
> 
> const req = new XMLHttpRequest();
> req.upload.onprogress = updateProgress;
> req.upload.onload = transferComplete;
> // You might want to also listen to onabort, onerror, ontimeout
> req.open("POST", url);
> for (const [key, value] of Object.entries(headers)) {
>   req.setRequestHeader(key, value);
> }
> req.send(data);
> 
> function updateProgress(e) {
>   const pct = (e.loaded / e.total) * 100;
>   console.log(`Upload progress = ${e.loaded} / ${e.total} = ${pct}`);
> }
> 
> function transferComplete(e) {
>   console.log("The transfer is complete.");
> }
> ```
> 
> Some of the code above is directly from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#monitoring_progress).
> 
> Note that events for listening to uploads are on [XMLHttpRequest.upload](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload) and events for listening to downloads are on [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#events).

What is the `supabase._getAuthHeaders()` method you are using?

**Comment by Nisthar** [comment]
> In case it's helpful for others, here's an approach for getting upload progress with XMLHttpRequest in the browser.
> 
> In place of:
> 
> ```
> await supabase.storage.from(bucket).upload(path, data);
> ```
> 
> you could instead do the below:
> 
> ```
> // Typescript will give errors for accessing protected members of supabase
> const url = `${supabase.supabaseUrl}/storage/v1/object/${bucket}/${path}`;
> const headers = supabase._getAuthHeaders();
> 
> const req = new XMLHttpRequest();
> req.upload.onprogress = updateProgress;
> req.upload.onload = transferComplete;
> // You might want to also listen to onabort, onerror, ontimeout
> req.open("POST", url);
> for (const [key, value] of Object.entries(headers)) {
>   req.setRequestHeader(key, value);
> }
> req.send(data);
> 
> function updateProgress(e) {
>   const pct = (e.loaded / e.total) * 100;
>   console.log(`Upload progress = ${e.loaded} / ${e.total} = ${pct}`);
> }
> 
> function transferComplete(e) {
>   console.log("The transfer is complete.");
> }
> ```
> 
> Some of the code above is directly from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#monitoring_progress).
> 
> Note that events for listening to uploads are on [XMLHttpRequest.upload](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload) and events for listening to downloads are on [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#events).

idk why but my upload using this code is very slow.

**Comment by iampopal** [comment]
We need this on Flutter Package!!!

**Comment by DeabitTech** [comment]
yeah never i can upload file of up to 90mb , fix it please

**Comment by isaiasmatewos** [comment]
In case someone is still interested, use this function downloads files from Supabase storage and tracks download progress: 

`Future<void> _downloadFileWithProgress(Map<String, String> headers,
      String bucketId, String path, File downloadPath) async {
    try {
      setState(() {
        _downloading = true;
      });

      final _path = _getFinalPath(bucketId, path);
      final options = FetchOptions(headers: headers, noResolveJson: true);

      final url = '${supabase.storage.url}/object/$_path';

      final request = http.Request('GET', Uri.parse(url))
        ..headers.addAll(headers)
        ..body = json.encode({});

      final response = request.send();

      List<List<int>> chunks = [];
      int downloaded = 0;

      response.asStream().listen((event) {
        event.stream.listen(
          (value) {
            // Display perecentage of completion
            debugPrint(
                'downloadPercentage: ${downloaded / (event.contentLength ?? 0) * 100}');

            chunks.add(value);
            downloaded += value.length;

            setState(() {
              _downloadProgress = downloaded / (event.contentLength ?? 0);
            });
          },
          onDone: () async {
            // Display perecentage of completion
            debugPrint(
                'downloadPercentage: ${downloaded / (event.contentLength ?? 0) * 100}');

            // Save the file
            final Uint8List bytes = Uint8List(event.contentLength ?? 0);
            int offset = 0;

            for (List<int> chunk in chunks) {
              bytes.setRange(offset, offset + chunk.length, chunk);
              offset += chunk.length;
            }

            await downloadPath.create(recursive: true);
            await downloadPath.writeAsBytes(bytes);

            setState(() {
              _downloading = false;
            });
          },
        );
      });
    } catch (e) {
      debugPrint(e.toString());
    }
  }`

**Comment by isaiasmatewos** [comment]
In case someone interested, I wrote this function to download from Supabase storage and track download progress:

https://gist.github.com/isaiasmatewos/c15c4d75ce501437bd2be6eea6d0acb9

**Comment by Devosaure** [comment]
An absolute must have for these case where users must upload large files, we need to have a way to give them feedbacks on their upload progress. Thanks!

**Comment by iampopal** [comment]
Can you please give us an example about showing uploading progress to user
based on uploaded file…
This is a very must functionality we need..

**Comment by colestriler** [comment]
Any update?

**Comment by songhn233** [comment]
I also think this is a much-needed feature, and the supbase dashboard supports the display of progress when uploading files.

Maybe some examples should be provided?

**Comment by cameronk** [comment]
Hey, wanted to share how I was able to do this with React & Axios (much cleaner API than raw XMLHttpRequest) without too much trouble.

```
import axios from "axios";
import type { Axios, AxiosRequestConfig } from "axios";

async upload(file: File, bucket: string, name: string, config?: AxiosRequestConfig) {
  // Create form data
  const blob = new Blob([file], { type: "video/mp4" });
  const formData = new FormData();
  formData.append('cacheControl', '3600');
  formData.append('', blob);

  return axios.post(
    `${BASE_SUPA_URL}/storage/v1/object/${bucket}/${name}`,
    formData,
    {
      headers: {
        "Content-Type": "multipart/form-data",
        // @ts-ignore
        ...supabase.headers,
      },
      onUploadProgress: config?.onUploadProgress,
      onDownloadProgress: config?.onDownloadProgress,
    }
  );
}```
```
const upload = await api.upload(
  file,
  "artifacts",
  `${fileID}/video.mp4`,
  {
    onUploadProgress: (evt) => {
      const _progress = (evt.loaded / (evt.total || Infinity)) * 100;
      console.log(_progress)
      setProgress(_progress)
    }
  }
);
```

One note: I'm uploading to a local Supabase instance in Docker and had to set a RLS policy via the UI for this to work: http://localhost:54323/project/default/storage/policies

I used the "Enable insert for authenticated users only" template. Haven't tested any other RLS policies but seems that `supabase.headers` has everything necessary.

**Comment by iampopal** [comment]
Gloat seeing you did this with javaScript, how will we able check upload
progress with dart package?

**Comment by RieMars** [comment]
@cameronk I tried your solution but first I'm getting errors:
`error: "Error", "headers must have required property 'authorization'"`

so I then tried using:
`...supabase.auth.headers`

yet that was giving me a different error of:
`error: "Invalid JWT", message: "new row violates row-level security policy for table \"objects\""

I have the same policy you suggested and tried a few other combinations too, also double checking the bucket name, to no avail. But thanks for at least putting me in the right direction with your snippets.

**Comment by paladyne-io** [comment]
The example provided by [grschafer] above was working for me with Supabase V1 but after recently upgrading to V2 it barfed on this line:

> const headers = supabase._getAuthHeaders();

After replacing it with: 'const headers = supabaseClient.auth.headers'

it is working again. I made uploaders and downloaders for vue.js (using with Quasar).I hope they help someone.

[SupabaseUploaderDownloeder.zip](https://github.com/supabase/storage-api/files/10857887/SupabaseUploaderDownloeder.zip)

**Comment by inian** [comment]
Hi, with [resumable uploads](https://supabase.com/docs/guides/storage/uploads#resumable-upload), there is a native way to listen to progress events now.

**Comment by softmarshmallow** [comment]
> Hi all, with [resumable uploads](https://supabase.com/docs/guides/storage/uploads#resumable-upload), there is a native way to listen to progress events now.

Correct link: https://supabase.com/docs/guides/storage/uploads/resumable-uploads?queryGroups=language&language=js

**Comment by JulioMacedo0** [comment]
> > > Hi all, with [resumable uploads](https://supabase.com/docs/guides/storage/uploads#resumable-upload), there is a native way to listen to progress events now.
> > 
> > 
> > Correct link: https://supabase.com/docs/guides/storage/uploads/resumable-uploads?queryGroups=language&language=js
> 
> any way to use resumable uploads feature in flutter?

You can use the TUS client for Dart. In the Supabase examples, they use the TUS package in JavaScript, but I believe you can achieve the same result using the package made for Dart.

[TUS client for Dart](https://pub.dev/packages/tus_client_dart)

**Comment by Obeyed** [comment]
Just leaving this here for reference. To avoid expired tokens, it's a good idea to add the session token in the `onBeforeRequest` hook on the `tus.Upload` for every request.  See https://github.com/tus/tus-js-client/blob/main/docs/api.md#onbeforerequest

**Comment by dss1210** [comment]
`
// Set filename
const url = `${supabase.supabaseUrl}/storage/v1/object/songs/${fn}`
// Headers
const headers = supabase.auth.headers

const req = new XMLHttpRequest()

req.upload.onprogress = updateProgress
req.upload.onload = transferComplete

// You might want to also listen to onabort, onerror, ontimeout
req.open('POST', url)
for (const [key, value] of Object.entries(headers)) {
  req.setRequestHeader(key, value)
}
req.send(file)

function updateProgress(e) {
  const pct = (e.loaded / e.total) * 100
  console.log(`Upload progress = ${e.loaded} / ${e.total} = ${pct}`)
}

function transferComplete(e) {
  console.log('The transfer is complete.')
}
`
