### ISSUE TITLE
Storage v3 - Resumable uploads error

### ISSUE THREAD

**Issue by DanielAlcaraz** [supabase/storage-api#331]
# Bug report

- [ X] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I was reading the blog about the new storage features. I found interesting that you implemented the Tus protocol. I was trying to build a simple demo with Uppy as you show in the blog but I get a 404 error.

[https://supabase.com/blog/storage-v3-resumable-uploads#deep-dive-into-resumable-uploads](https://supabase.com/blog/storage-v3-resumable-uploads#deep-dive-into-resumable-uploads)

## To Reproduce

I created a simple Codesandbox with Svelte and I added the code inside the layout file:

[https://codesandbox.io/p/sandbox/muddy-cache-xr8ct2?welcome=true](https://codesandbox.io/p/sandbox/muddy-cache-xr8ct2?welcome=true)

I didn't add the anon key and my project ref.

I get this error:
`{"message":"Route POST:/upload/resumable not found","error":"Not Found","statusCode":404}`

I guess the URL is not correct? But I could't figure out how to make this work.

## Expected behavior

I expect to be able to upload a JPG inside my bucket folder.

## Additional context

I also tried to create an upload URL with the Js Client using `store.createSignedUploadUrl`. It doesn't give the HTTP error anymore but I get an error message inside the Uppy component saying the `Location` header is missing.

The bucket is public and I created this 2 policies:

```
 create policy "Public Access Bucket Images Get"
on storage.objects for select
using ( bucket_id = 'users' );

create policy "Public Access Bucket Images Post"
on storage.objects for insert
with check ( bucket_id = 'users' );
```

I don't know if they are correct. I just want to allow to upload files for the authenticated users. I tried to make the buket open to test if everything works well.

Thank you.

**Comment by fenos** [comment]
Yes, that's correct! If you reach out to us we will enable it for you

We are going to release it globally very soon

**Comment by Obeyed** [comment]
@fenos Are there any resources on how to use resumable uploads when self-hosting? 

I tried to follow this guide: https://supabase.com/docs/guides/storage/uploads#resumable-upload but hit two challenges:

- first, when using an upload url with a specific port, that port is ignored when the storage server tries to upload the following chunks. That means if I use `http://localhost:8000/storage/v1/upload/resumable` it will strip the `:8000` from the url, making it fail.
- secondly, when the first issue is circumvented, the upload actually progresses, but before completing the following error happens: 

```
Mixed Content: The page at 'https://xxxx' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://<a-kong-gateway-domain>/upload/resumable/<some-resumable-upload-id>'. This request has been blocked; the content must be served over HTTPS.
```

One thing to notice as well is that the `storage/v1` part of the url has been stripped for some reason. I assume it would have failed regardless of it being requested with http instead of https.

I'm using the [supabase/storage-api:v0.41.5](https://hub.docker.com/layers/supabase/storage-api/v0.41.5/images/sha256-8a8314fde97066e4122ad5e1e10a8d7b043ac5da7d1761d6c7b9ace104215809) docker image.

**Comment by fenos** [comment]
Hi @Obeyed 

The storage server is set up to run behind a reverse proxy or load balancer, that forwards the x-forwarded headers. 
but it can be run on localhost too, there are 2 simple steps to run TUS with the server.

1) Make sure the reverse proxy is setting x-forwarded headers

In your case, it seems you are using Kong, but it is not forwarding the headers correctly.
If you are using this setup on your local machine without a domain you might need to use this trick that we implemented on our local development: https://github.com/supabase/cli/blob/main/internal/start/templates/kong.yml#L88

In production, the headers should be sent properly with the correct domain and host so you don't need the above change.

2) Customise the TUS_URL_PATH env

in order to have the `storage/v1` included you need to set the env variable `TUS_URL_PATH` on the storage-api server to `/storage/v1/upload/resumable`

let me know if this works for you 👍

**Comment by Obeyed** [comment]
@fenos Really appreciate the response and help! Got it working. :raised_hands: 

I added the `TUS_URL_PATH` and didn't have to include the `/storage/v1` in the kong config. So I ended up with the following.

When running locall, I added this to the `kong.yml` under the storage service:

```
      - name: request-transformer
        config:
          add:
            headers:
              - "Forwarded: host=localhost:8000;proto=http"
```

On a server with nginx as reverse proxy, I tried this, and it worked. _(I couldn't figure out how to make nginx / kong forward the protocol correctly without this)_.

```
      - name: request-transformer
        config:
          add:
            headers:
              - "Forwarded: proto=https"
```

I presume that if I'm running the servers behind a load balancer, then I would add the "host" part and set it to the domain pointing to the load balancer.

If you know any resources on what the best configuration with nginx is, then please do share. I'm using Docker Swarm to orchestrate the services.

Do you know why there's a hard limit of 6mb for the chunk size? The docs just say this is currently a limitation with the storage-api, but adds no further explanation. Would be cool to understand more. :smile:  Thanks again!

**Comment by fenos** [comment]
@Obeyed Glad you got it working!

In terms of configurations, as far as the x-forwarded-proto and x-forwarded-host are sent over to the storage-api the corresponding host and protocol will be used.


> Do you know why there's a hard limit of 6mb for the chunk size? The docs just say this is currently a limitation with the storage-api, but adds no further explanation. Would be cool to understand more. 😄 Thanks again!

Sure, the reason behind the 6MB limit is that S3 imposes the part size upload to be a minimum of 5MB and a maximum of 5GB we chose to go with 6MB since for large files seems the right middle ground

https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html

with a 6MB chunk and 1000 parts limits we can handle up to 60GB file uploads

**Comment by urania-dev** [comment]
> @fenos Really appreciate the response and help! Got it working. 🙌
> 
> I added the `TUS_URL_PATH` and didn't have to include the `/storage/v1` in the kong config. So I ended up with the following.
> 
> When running locall, I added this to the `kong.yml` under the storage service:
> 
> ```
>       - name: request-transformer
>         config:
>           add:
>             headers:
>               - "Forwarded: host=localhost:8000;proto=http"
> ```
> 
> On a server with nginx as reverse proxy, I tried this, and it worked. _(I couldn't figure out how to make nginx / kong forward the protocol correctly without this)_.
> 
> ```
>       - name: request-transformer
>         config:
>           add:
>             headers:
>               - "Forwarded: proto=https"
> ```
> 
> I presume that if I'm running the servers behind a load balancer, then I would add the "host" part and set it to the domain pointing to the load balancer.
> 
> If you know any resources on what the best configuration with nginx is, then please do share. I'm using Docker Swarm to orchestrate the services.
> 
> Do you know why there's a hard limit of 6mb for the chunk size? The docs just say this is currently a limitation with the storage-api, but adds no further explanation. Would be cool to understand more. 😄 Thanks again!

This. i looked everywhere, tinkered with traefik for six hours, then i remembered reading this. it works <3

**Comment by jackson-jackson** [comment]
> {"message":"Route POST:/upload/resumable not found","error":"Not Found","statusCode":404}

Do we still need to request access?

**Comment by jackson-jackson** [comment]
@fenos do we still need to request access?

**Comment by GaryAustin1** [comment]
@jackson-jackson v3 should be out on instances for awhile now.  Certainly any new instances in the past couple of months.
You MAY need to upgrade the database or pause/restore an older instance, but not sure on this specific update.

**Comment by olee** [comment]
I'm having the same issue with uploads to storage not returning the correct proxy url:
![image](https://github.com/supabase/storage/assets/6547794/b1536aa3-5981-4b7f-8545-ea1f07ec8edf)

I tried the fix @Obeyed proposed [here](https://github.com/supabase/storage/issues/331#issuecomment-1672123240) but it still doesn't work at all.
Why would we even have to add the "Forwarded" header when there are already proper "X-Forwarded-*" headers sent to storage api?

**Comment by AntonOfTheWoods** [comment]
This is more than a little infuriating... 

So it was actually working (a file is definitely uploaded and visible in the studio!) *without* the `Forwarded: ...` and then once it stops working, namely it goes from correctly using `https` to suddenly using `http` for the `supabase`/`kong` generated links. It doesn't seem to matter what I put in the `kong` config, it won't come back. Setting `NODE_ENV === 'production'` doesn't seem to help either.

I have tried adding this to `kong` in my kubernetes helm chart:

```
      - name: request-transformer
        config:
          add:
            headers:
              - "Forwarded: proto=https"
```

But this just has no effect. I checked and the `kong` config file is definitely updated in the container...

**Comment by btouchard** [comment]
Hello
I have Supabase with Storage behind a Traefik reverse proxy.
I spent 10 hours trying to solve this problem after updating Supabase Storage.
Impossible to make TUS work with Storage version 1.10.1 or higher, so I used version 1.9.1, which works, if you configure Kong with this:

```yaml
      - name : request-transformer
        config :
          add :
            headers :
              - 'Forwarded: host=\$(headers.host)/storage/v1;proto=https'
```

and `TUS_URL_PATH=/upload/resumable` in environment variables

**Comment by tothster** [comment]
> > Hello I have Supabase with Storage behind a Traefik reverse proxy. I spent 10 hours trying to solve this problem after updating Supabase Storage. Impossible to make TUS work with Storage version 1.10.1 or higher, so I used version 1.9.1, which works, if you configure Kong with this:
> > ```yaml
> >       - name : request-transformer
> >         config :
> >           add :
> >             headers :
> >               - 'Forwarded: host=\$(headers.host)/storage/v1;proto=https'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and `TUS_URL_PATH=/upload/resumable` in environment variables
> 
> Same for me. 4 hours to finally downgrade to 1.9.1

Didn't work for me even with the modifications in kong.yml, `TUS_URL_PATH` in .env, and the downgrade.
The environment variable is to be included in the .env file on the docker folder, right? My browser keeps hitting localhost:8000/storage/v1/upload/resumable.

**Comment by Obeyed** [comment]
I'm not up to date on this thread. Wouldn't the `KONG_PORT_MAPS` environment variable be useful here to tell Kong which port the requests are coming from? See [Kong configuration docs on port_maps](https://docs.konghq.com/gateway/latest/reference/configuration/#port_maps)
